config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'transactions', to: 'transactions#index'
  post 'transactions', to: 'transactions#fetch'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :transactions
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
  @city = City.find_by(postal_code: params.require(:zip_code))
  if !@city
    fetch
  end
  end

  def fetch
    JSON.parse(Typhoeus.get("https://data.opendatasoft.com/api/records/1.0/search/?dataset=demande-de-valeurs-foncieres-agrege-a-la-transaction%40public&q=&facet=code_postal&refine.code_postal=#{params.require(:zip_code)}").response_body)['records'].each do |record|
    @city = City.find_by(postal_code: params[:zip_code] ) || City.create(postal_code:  record['fields']['code_postal'], name:  record['fields']['commune'])
          tr = @city.transactions.find_or_create_by(record_id: record['recordid'])
          tr.update({
            transaction_date: record['fields']['date_mutation'],
            address: "#{record['fields']['no_voie']} #{record['fields']['type_de_voie']} #{record['fields']['voie']}, #{record['fields']['code_postal']} #{record['fields']['commune']}",
            estate_type: record['fields']['type_local'],
            total_area: record['fields']['surface_reelle_bati'],
            number_of_rooms: record['fields']['nombre_pieces_principales'],
            value: record['fields']['valeur_fonciere'],
          }
          )
  end; render :index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @cities = City.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Home Pricer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1>Home pricer</h1>
    <br />
    <br />
    <%= yield %>
  </body>
</html>

app/views/transactions/index.html.erb
<%= link_to '< Retour', welcome_index_path, method: :get %>
<br />
<br />
Transactions enregistrées dans la commune : <%= @city&.name %> (<%= @city&.postal_code || params[:zip_code] %>)
<%= form_with url: transactions_path, method: :post do |form| %>
  <%= form.hidden_field :zip_code, value: @city&.postal_code || params[:zip_code] %>
  <%= submit_tag 'Synchroniser les transactions' %>
<% end %>
<br />
<table border=1>
  <tr>
    <th>Date</th>
    <th>Adresse</th>
    <th>Type</th>
    <th>Surface bâti</th>
    <th>Nombre pièces</th>
    <th>Valeur</th>
  </tr>
  <% @city&.transactions&.each do |record| %>
      <tr>
        <td><%= record.transaction_date%></td>
        <td><%= record.address%></td>
        <td><%= record.estate_type%></td>
        <td><%= record.total_area%></td>
        <td><%= record.number_of_rooms%></td>
        <td><%= record.value%> €</td>
      </tr>
  <% end %>
</table>

app/views/welcome/index.html.erb
<h3>Villes synchronisées :</h3>
<table border=1>
  <tr>
    <th>Code postal</th>
    <th>Nom</th>
  </tr>
  <% @cities.each do |record| %>
      <tr>
        <td><a href="/transactions?zip_code=<%= record.postal_code %>"><%= record.postal_code %></a></td>
        <td><a href="/transactions?zip_code=<%= record.postal_code %>"><%= record.name %></a></td>
      </tr>
  <% end %>
</table>
<br />

<h3>Nouvelle ville :</h3>
<%= form_with url: transactions_path, method: :get do |form| %>
    <%= form.label :zip_code, "Code postal" %>
    <%= form.text_field :zip_code %>
    <%= submit_tag 'Synchroniser' %>
<% end %>